---
apiVersion: v1
kind: Service
metadata:
  name: paid-dapp-nextjs
  labels:
    app: dapp
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: dapp
  type: LoadBalancer